### ISSUE TITLE
Environments are likely broken or might break soon

### ISSUE THREAD

**Issue by johanneskoester** [jbudis/snakelines#82]
Dear devs,
at least some of the environments in your repo look like this:

```yaml
channels:
- bioconda
dependencies:
- soapdenovo2=2.40
```

This has two issues:
1. Bioconda is built against conda-forge, which is missing here. This is likely to break when the defaults channel looses binary compatibility with conda-forge. This happens from time to time. conda-forge should be added (and it should be added as the first channel in the list, as there are some old packages in both channels which can otherwise cause problems when people have activated strict channel priorities).
2. You should even explicitly deactivate the defaults channel (by adding nodefaults to the bottom). This way, the environment is solved in the same deterministic way, regardless of whether people have activated or deactivated strict channel priorities.

In total, all the environments should rather look like this:

```yaml
channels:
- conda-forge
- bioconda
- nodefaults
dependencies:
- soapdenovo2=2.40
```
